services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mottu-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrator
      args:
        DB_CONNECTION: ${DB_CONNECTION}
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mottu-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_CONNECTION: ${DB_CONNECTION}
    ports:
      - "5248:80"
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DB_CONNECTION: ${DB_CONNECTION}
    networks:
      - mottu-net

volumes:
  pgdata:

networks:
  mottu-net: