FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY . .

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

ARG DB_CONNECTION
ENV DB_CONNECTION=$DB_CONNECTION

RUN dotnet restore MottuApi.csproj

CMD ["dotnet", "ef", "database", "update"]